### ISSUE TITLE
Indentation module gets confused on method declarations in certain cases

### ISSUE THREAD

**Issue by Algomorph** [Algomorph/CodeStyleGradingAid#11]
Case: method declaration in the code with Allman brace style and `package` visibility (see example below) gets miss-classified as a non-terminating statement, whereas it should be classified as an opening scope.

```Java
void GoToCampus(bool useBike)
{
    //implementation
}
```

Proposed solution: before traversing the `tr` code lines, run a simple analysis on type AST nodes from the parser and method declaration nodes within them (recursion might be needed to handle inner types' methods) and, for each discovered `MethodDeclaration` node, insert the line numbers between (and including) `location.start.line` and `location.end.line` into a `Set` object. When discriminating whether the line is a method declaration or a non-terminated statement, simply check if the mentioned set includes (`.has(...)`) the line number (marked as a method declaration).

**Comment by Algomorph** [comment]
Test case: kdarakhs, P2, line 6 of WebPage.java

**Comment by msimmon6** [comment]
Not actually a test case, line 5 is a non-terminated statement and expects two indents on line 6. This is how it is supposed to act for now, since (although I have an idea for doing it) I don't want to implement checking how they perform a standard indent in that case.

**Comment by msimmon6** [comment]
Also it turns out I'm dumb and the thing I was doing to check public/protected/private was a major overcorrection - I already had a check in code to see if it was an Allman. I submitted a sample of this in my AnchorElement. I think this works as expected.
