### ISSUE TITLE
Indentation module: lots of what seems to be false positives (whole files of them?) for some submissions

### ISSUE THREAD

**Issue by Algomorph** [Algomorph/CodeStyleGradingAid#19]
Test case: src/model/HeadingElement.java of jwang086, P2 and many others.

**Comment by msimmon6** [comment]
![image](https://user-images.githubusercontent.com/72671782/95794710-8af7aa00-0cb6-11eb-9c33-3ec5fa0ab307.png)
Looks fine to me, maybe I fix it in my latest commit?

**Comment by Algomorph** [comment]
(Resolved, that was the other jwang, see the correct jwang)

**Comment by msimmon6** [comment]
3 issues total fixed:
- No longer discard braces before starting comments
- No longer fail to detect non-leading '}' when no '{' are present
- Convert HTML code correctly

**Comment by Algomorph** [comment]
I'm still getting this on master branch, see P2 of kanand1.

**Comment by msimmon6** [comment]
Yeah, this will keep happening whenever a case I never considered happens (case in point - now fixes case when unbraced statement is on the same line as the code, e.g. "else foo;"). This file works now, we just need to keep looking for where it breaks.
