### ISSUE TITLE
Indentation Module - "{", "}" in Strings

### ISSUE THREAD

**Issue by msimmon6** [Algomorph/CodeStyleGradingAid#23]
The way I choose the next indentation is by counting the number of {'s and }'s in a line, then modifying accordingly. However, as you can see in my (msimmon6) submission #9 of Project 2a, line 37 of AnchorElement has "{ { }" as a string. I need to figure out a way to ignore characters that are inside strings. I feel like something simple like removing everything inside a string in the not-actual code would fix it, but I'm currently unsure if modifying the line would modify it in the HTML.

**Comment by Algomorph** [comment]
Back when I was working on the spacing module, I've added a method to `utils.js` for getting rid of strings in a code line (or replacing them with a dummy "variable" name, depending on arguments). Please, have a look.

**Comment by Algomorph** [comment]
P.S. the method returns a new string, i.e. it doesn't modify the original string.

**Comment by msimmon6** [comment]
Ok cool, should be fixed then!
