### ISSUE TITLE
Function to highlight part of code line should be made and used in indentation module

### ISSUE THREAD

**Issue by Algomorph** [Algomorph/CodeStyleGradingAid#4]
As @william8siew noted, indentation module would be more useful if incorrect indentation characters would be highlighted.
I propose the following behavior:

1) Keep the button-label as it is now (just put a space between # and "Expected ...")
2) Highlight the extra indentation characters in case indentation is too large for a particular line.
3) Highlight the entire indentation (all whitespace characters before any symbols) if case indentation is too little for a particular line.

Tak's old code already had a `highlightText` function (I moved it to `submit_server_ui.js`), this can probably be recycled in this function.  The `highlightLine` function right below it can probably be used for reference.

**Comment by msimmon6** [comment]
I did it :)
